# 🔬 LAB 3 — Setup vLLM: Llama 3.1 8B e Primeiro Completion Jurídico

**Curso:** MBA RAG & CAG Aplicados a Direito e Segurança Pública  
**Aula:** 1 — Fundamentos  
**Duração estimada:** 45 minutos  
**Ambiente:** Google Colab com GPU T4

---

## 🎯 Objetivo
1. Instalar e configurar o **vLLM** como servidor de inferência de alto desempenho
2. Servir o modelo **Llama 3.1 8B Instruct** via vLLM
3. Executar o primeiro completion com prompt jurídico
4. Comparar diferentes configurações de `temperature`
5. Usar a API OpenAI-compatível do vLLM com system messages
6. Expor o servidor vLLM via **ngrok** (para uso externo)

## ⚠️ Requisito
**GPU T4 obrigatória!** O Llama 3.1 8B requer ~16GB de VRAM (usaremos quantização AWQ).  
Verifique: Runtime → Tipo de runtime → GPU T4

---

## 🏗️ Arquitetura do Lab

```
Google Colab (GPU T4)
  └─ vLLM Server (porta 8000)
       ├─ Modelo: meta-llama/Meta-Llama-3.1-8B-Instruct
       ├─ API: OpenAI-compatível (/v1/completions, /v1/chat/completions)
       └─ ngrok tunnel → URL pública HTTPS (opcional)
```

> **🔒 Nota de Segurança:** O vLLM roda **completamente local** na GPU do Colab. Nenhum dado é enviado para servidores externos de LLM. Isso é essencial para processos sob sigilo judicial (LGPD, sigilo funcional).

---

## 🆚 Por que vLLM em vez de Ollama?

| Característica | vLLM | Ollama |
|----------------|------|--------|
| Throughput | ⚡ Alto (PagedAttention) | Médio |
| API OpenAI-compat. | ✅ Nativa | ✅ Nativa |
| Quantização | bfloat16, fp16, AWQ, GPTQ | GGUF/Q4 |
| Batching dinâmico | ✅ Sim | ❌ Não |
| Deploy produção | ✅ Recomendado | ⚠️ Dev/local |
| Integração HuggingFace | ✅ Direta | ❌ Indireta |

**vLLM** é o padrão de mercado para deploy de LLMs em produção (Kubernetes, GPU clusters). Aprendê-lo aqui prepara você para ambientes reais de segurança pública e jurídico.

## 📦 CÉLULA 1 — Verificar GPU e Instalar vLLM

**O que faz:** Verifica a GPU disponível, instala o vLLM e suas dependências.

**Por que:** O vLLM utiliza **PagedAttention** para gerenciar a VRAM de forma eficiente, permitindo servir modelos grandes com alto throughput. É necessário confirmar que a GPU T4 está disponível antes de iniciar.

> **⏱️ Tempo de instalação:** 3–5 minutos (o vLLM é um pacote grande com dependências CUDA).

In [5]:
# ─── CÉLULA 1: Verificar GPU e instalar vLLM ───────────────────
import subprocess, sys, os

print('🖥️  VERIFICAÇÃO DE GPU')
print('=' * 60)

# Verifica GPU via nvidia-smi
result = subprocess.run(['nvidia-smi', '--query-gpu=name,memory.total,driver_version',
                         '--format=csv,noheader'], capture_output=True, text=True)
if result.returncode == 0:
    gpu_info = result.stdout.strip()
    print(f'  GPU detectada: {gpu_info}')
else:
    print('  ❌ ATENÇÃO: GPU não detectada!')
    print('  → Vá em: Runtime → Tipo de runtime → GPU T4')
    raise RuntimeError('GPU T4 necessária para este laboratório.')

# Verifica memória disponível
mem_result = subprocess.run(['nvidia-smi', '--query-gpu=memory.free,memory.total',
                              '--format=csv,noheader,nounits'], capture_output=True, text=True)
if mem_result.returncode == 0:
    free_mb, total_mb = mem_result.stdout.strip().split(', ')
    print(f'  VRAM livre:   {int(free_mb):,} MiB')
    print(f'  VRAM total:   {int(total_mb):,} MiB')
    if int(free_mb) < 12000:
        print('  ⚠️  AVISO: Menos de 12GB livres. Reinicie o runtime para liberar memória.')
    else:
        print('  ✅ Memória suficiente para Llama 3.1 8B')

print()
print('📦 INSTALANDO vLLM...')
print('   (Este processo pode levar 3-5 minutos)')
print('=' * 60)

# Instala vLLM — versão compatível com CUDA 12 / PyTorch 2.x do COLAB
!pip install vllm==0.17.0 --extra-index-url https://download.pytorch.org/whl/cu128

# Instala cliente OpenAI (para usar a API do vLLM)
!pip install openai --quiet

# Instala pyngrok para exposição opcional
!pip install pyngrok --quiet

print()
print('✅ Instalação concluída!')

# Confirma versão do vLLM
import importlib
vllm_version = subprocess.run([sys.executable, '-c', 'import vllm; print(vllm.__version__)'],
                               capture_output=True, text=True)
print(f'   vLLM versão: {vllm_version.stdout.strip()}')

🖥️  VERIFICAÇÃO DE GPU
  GPU detectada: NVIDIA L4, 23034 MiB, 580.82.07
  VRAM livre:   22,564 MiB
  VRAM total:   23,034 MiB
  ✅ Memória suficiente para Llama 3.1 8B

📦 INSTALANDO vLLM...
   (Este processo pode levar 3-5 minutos)
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu128
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 4.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.9/87.9 kB 10.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 432.9/432.9 MB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.6/192.6 kB 22.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 155.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.0/111.0 kB 14.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/


✅ Instalação concluída!
   vLLM versão: 0.17.0


### 🔧 Troubleshooting — Célula 1:
| Erro | Causa | Solução |
|------|-------|---------|
| `RuntimeError: GPU T4 necessária` | Runtime sem GPU | Runtime → Tipo de runtime → GPU T4 |
| `ERROR: Could not find a version` | PyPI lento | Aguarde e reexecute; tente `--index-url https://pypi.org/simple` |
| `CUDA error: out of memory` | VRAM insuficiente | Reinicie o runtime (Runtime → Reiniciar runtime) |

## 📦 CÉLULA 2 — Configurar Credenciais e Iniciar Servidor vLLM

**O que faz:** Configura o token do HuggingFace (necessário para baixar Llama 3.1) e inicia o servidor vLLM em background.

**Por que:** O Llama 3.1 é um modelo com licença de uso restrito da Meta. É necessário:
1. Aceitar a licença em: https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct
2. Gerar um token em: https://huggingface.co/settings/tokens
3. Adicionar o token nos **Segredos do Colab** com nome `HF_TOKEN`

> **⏱️ Atenção:** O download + carregamento do modelo leva **8–15 minutos** na primeira execução.

---

### 🔑 Como configurar o HF_TOKEN no Colab:
1. Clique no ícone de 🔑 **Segredos** na barra lateral esquerda
2. Clique em **+ Adicionar novo segredo**
3. Nome: `HF_TOKEN`
4. Valor: seu token (começa com `hf_...`)
5. Ative o acesso ao notebook

In [1]:
# ─── CÉLULA 2: Configurar HF_TOKEN e iniciar servidor vLLM ────
import subprocess, time, os, requests

# ── 2.1 Carrega token HuggingFace dos Segredos do Colab ──────
def get_secret(nome):
    """Obtém segredo do Colab Secrets ou variável de ambiente."""
    try:
        from google.colab import userdata
        valor = userdata.get(nome)
        if valor:
            return valor
    except Exception:
        pass
    return os.environ.get(nome, '')

# HF_TOKEN = get_secret('HF_TOKEN')
HF_TOKEN = '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'
if not HF_TOKEN:
    print('❌ HF_TOKEN não configurado!')
    print('   Siga as instruções acima para configurar o token do HuggingFace.')
    raise ValueError('Configure HF_TOKEN nos Segredos do Colab.')
else:
    print(f'✅ HF_TOKEN carregado: {HF_TOKEN[:8]}...[oculto]')

# Exporta para o ambiente do processo filho (vLLM)
os.environ['HF_TOKEN'] = HF_TOKEN
os.environ['HUGGING_FACE_HUB_TOKEN'] = HF_TOKEN

# ── 2.2 Configuração do servidor vLLM ────────────────────────
MODELO_HF    = 'casperhansen/llama-3-8b-instruct-awq'  # Modelo Meta no HF
VLLM_PORT    = 8000
VLLM_URL     = f'http://localhost:{VLLM_PORT}'
GPU_MEM_FRAC = 0.70    # Usa 90% da VRAM — deixa 10% para overhead CUDA
MAX_CTX      = 4096    # Contexto de 4096 tokens (adequado para T4 16GB)
LOG_FILEPATH = '/tmp/vllm_server.log'

print()
print('🚀 INICIANDO SERVIDOR vLLM')
print('=' * 60)
print(f'  Modelo:         {MODELO_HF}')
print(f'  Porta:          {VLLM_PORT}')
print(f'  GPU utilização: {GPU_MEM_FRAC * 100:.0f}%')
print(f'  Contexto máx:   {MAX_CTX} tokens')
print(f'  Dtype:          awq (padrão para Llama 3.1)')
print(f'  Logs em:        {LOG_FILEPATH}')
print()
print('⏳ Aguardando download + carregamento do modelo...')
print('   (8–15 minutos na primeira execução)')
print()

# ── 2.3 Inicia o servidor vLLM em background ─────────────────
# Clear previous log content and open for append for the subprocess
with open(LOG_FILEPATH, 'w') as f:
    f.write(f'🚀 Starting vLLM server, logs redirected to {LOG_FILEPATH}\n')

vllm_log_file = open(LOG_FILEPATH, 'a') # Open in append mode for the subprocess

cmd = [
    'python', '-m', 'vllm.entrypoints.openai.api_server',
    '--model',                    MODELO_HF,
    '--port',                     str(VLLM_PORT),
    '--dtype',                    "half",
    '--gpu-memory-utilization',   str(GPU_MEM_FRAC),
    '--max-model-len',            str(MAX_CTX),
    '--trust-remote-code',
    "--quantization", "awq",
]

print(f"🚀 Disparando servidor vLLM em background, logs em {LOG_FILEPATH}...")
# Popen não bloqueia a execução da célula
process = subprocess.Popen(
    cmd,
    stdout=vllm_log_file,
    stderr=subprocess.STDOUT,
    text=False # Output is now binary to file, the log reader will handle text
)
# The vllm_log_file is kept open by the subprocess. It will be closed implicitly when the process exits.

✅ HF_TOKEN carregado: hf_QvQAr...[oculto]

🚀 INICIANDO SERVIDOR vLLM
  Modelo:         casperhansen/llama-3-8b-instruct-awq
  Porta:          8000
  GPU utilização: 70%
  Contexto máx:   4096 tokens
  Dtype:          awq (padrão para Llama 3.1)
  Logs em:        /tmp/vllm_server.log

⏳ Aguardando download + carregamento do modelo...
   (8–15 minutos na primeira execução)

🚀 Disparando servidor vLLM em background, logs em /tmp/vllm_server.log...


In [7]:
import threading
import time
import os
from IPython.display import display
import ipywidgets as widgets

# 1. Criamos um widget de saída dedicado para os logs
out = widgets.Output(layout={'border': '1px solid #444', 'height': '300px', 'overflow_y': 'scroll'})
display(out)
log_buffer = []
log_filepath = '/tmp/vllm_server.log' # Define log file path here

def tail_f(filepath, process_handle, inactivity_timeout_seconds=60, poll_interval=1):
    """
    Simulates 'tail -f' on a file, displaying new lines, and stops after
    inactivity or if the process terminates.
    """
    last_activity_time = time.time()
    with out:
        print(f"Log reader thread iniciado, monitorando: {filepath}")

    # Open the file and seek to the end
    try:
        with open(filepath, 'r') as f:
            f.seek(0, os.SEEK_END) # Go to the end of the file

            while True:
                # Check if the process has terminated
                if process_handle.poll() is not None:
                    # Process terminated, read any remaining output
                    remaining_output = f.read()
                    if remaining_output:
                        for line in remaining_output.splitlines():
                            clean_line = line.strip()
                            if clean_line:
                                log_buffer.append(clean_line)
                                with out:
                                    if len(log_buffer) > 100:
                                        log_buffer.pop(0)
                                        out.clear_output(wait=True)
                                        print("\\n".join(log_buffer))
                                    else:
                                        print(clean_line)
                    with out:
                        print(f"\\n🏁 Processo vLLM terminou (código: {process_handle.returncode}). Leitor de logs finalizado.")
                    break # Exit loop

                new_lines_found = False
                line = f.readline()
                if line:
                    clean_line = line.strip()
                    if clean_line:
                        log_buffer.append(clean_line)
                        with out:
                            if len(log_buffer) > 100:
                                log_buffer.pop(0)
                                out.clear_output(wait=True)
                                print("\\n".join(log_buffer))
                            else:
                                print(clean_line)
                        new_lines_found = True
                        last_activity_time = time.time() # Reset inactivity timer
                else:
                    # No new lines, check for inactivity timeout
                    if time.time() - last_activity_time > inactivity_timeout_seconds:
                        with out:
                            print(f"\\n⏳ Leitor de logs finalizado após {inactivity_timeout_seconds} segundos de inatividade (sem novas linhas).")
                        break
                    # Sleep before trying to read again
                    time.sleep(poll_interval) # Poll every 'poll_interval' seconds

    except FileNotFoundError:
        with out:
            print(f"❌ Erro: Arquivo de log não encontrado: {filepath}")
    except Exception as e:
        with out:
            print(f"❌ Erro no leitor de logs: {e}")


# 2. Dispara a thread (assumindo que 'process' já foi criado em cell-5)
thread = threading.Thread(
    target=tail_f,
    args=(log_filepath, process, 60), # 60 segundos de timeout de inatividade
    daemon=True
)
thread.start()
print(f"🚀 Servidor vLLM disparado. Logs sendo monitorados de {log_filepath} abaixo (área rolável):")
# A execução do Colab continua livre aqui embaixo!

Output(layout=Layout(border='1px solid #444', height='300px', overflow_y='scroll'))

🚀 Servidor vLLM disparado. Logs sendo monitorados de /tmp/vllm_server.log abaixo (área rolável):


In [5]:
import requests
import time

url = "http://localhost:8000/health"

for i in range(15):
    try:
        response = requests.get(url)
        if response.status_code == 200:
            print("🔥 Sucesso! O servidor vLLM está online e respondendo.")
            break
    except requests.exceptions.ConnectionError:
        print(f"⏳ Aguardando o modelo carregar... (Tentativa {i+1}/10)")
        time.sleep(5)
else:
    print("❌ O servidor não respondeu após o tempo limite.")

🔥 Sucesso! O servidor vLLM está online e respondendo.


### 🔧 Troubleshooting — Célula 2:
| Erro | Causa | Solução |
|------|-------|---------|
| `ValueError: Configure HF_TOKEN` | Token ausente | Adicione `HF_TOKEN` nos Segredos do Colab |
| `401 Unauthorized` no HuggingFace | Token inválido ou licença não aceita | Acesse https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct e aceite a licença |
| `CUDA out of memory` no log | VRAM insuficiente | Reinicie o runtime; reduza `MAX_CTX` para 2048 |
| Servidor não inicia em 15min | Download lento | Verifique log: `!tail -20 /tmp/vllm_server.log` |

## 📦 CÉLULA 3 — Primeiro Completion: Análise Jurídica

**O que faz:** Executa a primeira geração de texto com o Llama 3.1 8B via vLLM, usando um prompt jurídico.

**Por que:** Demonstra o funcionamento básico da API `/v1/chat/completions` do vLLM, que é 100% compatível com o cliente OpenAI — o mesmo código funciona com GPT-4, Claude ou qualquer LLM servido pelo vLLM.

In [6]:
# ─── CÉLULA 3: Primeiro completion — análise jurídica ──────────
from openai import OpenAI
import time

# Cliente OpenAI apontando para o vLLM local
# Nota: api_key pode ser qualquer string (vLLM não valida por padrão)
client_vllm = OpenAI(
    base_url=f'{VLLM_URL}/v1',
    api_key='vllm-local'
)

# Consulta o ID exato do modelo servido pelo vLLM
modelos_disponiveis = client_vllm.models.list()
MODEL_ID = modelos_disponiveis.data[0].id
print(f'🤖 Usando modelo: {MODEL_ID}')
print('=' * 60)

# ── Prompt jurídico de teste ──────────────────────────────────
SYSTEM_PROMPT = (
    'Você é um assistente jurídico especializado em direito penal brasileiro. '
    'Responda sempre de forma técnica e concisa, citando artigos de lei quando aplicável. '
    'NUNCA invente precedentes, súmulas ou artigos inexistentes.'
)

USER_PROMPT = (
    'Qual é a diferença entre os crimes de furto (art. 155 CP) '
    'e roubo (art. 157 CP)? Explique os elementos que os distinguem '
    'e cite um exemplo prático de cada.'
)

print(f'📝 Pergunta: {USER_PROMPT[:80]}...')
print('⏳ Aguardando resposta do vLLM...')
print()

inicio = time.time()

resposta = client_vllm.chat.completions.create(
    model=MODEL_ID,
    messages=[
        {'role': 'system', 'content': SYSTEM_PROMPT},
        {'role': 'user',   'content': USER_PROMPT}
    ],
    temperature=0.2,    # Baixa temperatura para precisão jurídica
    max_tokens=500,
)

tempo_total = time.time() - inicio
texto_resposta = resposta.choices[0].message.content

# Métricas de geração
tokens_prompt    = resposta.usage.prompt_tokens
tokens_resposta  = resposta.usage.completion_tokens
tokens_total     = resposta.usage.total_tokens
tok_por_segundo  = tokens_resposta / tempo_total if tempo_total > 0 else 0

print('📊 MÉTRICAS DE GERAÇÃO:')
print(f'   Tokens (prompt):    {tokens_prompt}')
print(f'   Tokens (resposta):  {tokens_resposta}')
print(f'   Tokens (total):     {tokens_total}')
print(f'   Tempo total:        {tempo_total:.1f}s')
print(f'   Velocidade:         {tok_por_segundo:.1f} tokens/s')

print()
print('🗒️  RESPOSTA DO MODELO:')
print('-' * 60)
print(texto_resposta)
print('-' * 60)

🤖 Usando modelo: casperhansen/llama-3-8b-instruct-awq
📝 Pergunta: Qual é a diferença entre os crimes de furto (art. 155 CP) e roubo (art. 157 CP)?...
⏳ Aguardando resposta do vLLM...

📊 MÉTRICAS DE GERAÇÃO:
   Tokens (prompt):    119
   Tokens (resposta):  445
   Tokens (total):     564
   Tempo total:        66.8s
   Velocidade:         6.7 tokens/s

🗒️  RESPOSTA DO MODELO:
------------------------------------------------------------
De acordo com o Código Penal Brasileiro, os crimes de furto e roubo são dois tipos de crimes contra o patrimônio, mas com características diferentes.

O crime de furto (art. 155, CP) é caracterizado pela apropriação de coisa alheia móvel, mediante fraude ou abuso de confiança, sem violência ou ameaça. Para que o crime de furto seja configurado, é necessário que o agente tenha obtido a posse da coisa alheia mediante fraude ou abuso de confiança.

Exemplo prático: João, com o intuito de obter a posse de um relógio de ouro, apresenta-se como um comprador à v

### 📤 Output Esperado (Célula 3):
```
🤖 Usando modelo: meta-llama/Meta-Llama-3.1-8B-Instruct
============================================================
📊 MÉTRICAS DE GERAÇÃO:
   Tokens (prompt):    87
   Tokens (resposta):  312
   Tokens (total):     399
   Tempo total:        8.4s
   Velocidade:         37.1 tokens/s

🗒️  RESPOSTA DO MODELO:
------------------------------------------------------------
**Furto (art. 155 CP)** e **roubo (art. 157 CP)** diferem principalmente...
```

> **💡 Insight:** O vLLM é significativamente mais rápido que o vLLM na T4 — esperamos 30–60 tokens/s versus 10–20 tokens/s do vLLM, graças ao **PagedAttention** e ao **batching contínuo**.

## 📦 CÉLULA 4 — Experimento: Impacto da Temperature

**O que faz:** Executa o mesmo prompt com diferentes valores de `temperature` e compara os resultados.

**Por que:** A `temperature` é o parâmetro mais crítico para sistemas jurídicos. Valores altos geram respostas criativas mas potencialmente imprecisas — inaceitável em análise de evidências ou fundamentação de decisões.

In [8]:
# ─── CÉLULA 4: Experimento de temperature ─────────────────────
import time
import sys

PROMPT_CLASSIFICACAO = (
    'Classifique o seguinte crime segundo o Código Penal Brasileiro. '
    'Responda qual tipo do crime, Artigo e Pena máxima\n\n'
    'FATO: "O suspeito subtraiu R$ 500,00 da bolsa da vítima enquanto ela dormia no ônibus."'
)

TEMPERATURAS = [
    (0.0, 'Determinístico — máxima precisão'),
    (0.3, 'Baixo — recomendado para análise jurídica'),
    (0.7, 'Médio — equilíbrio criatividade/precisão'),
    (1.0, 'Alto — criativo, menos adequado para direito'),
]

print('🌡️  EXPERIMENTO: IMPACTO DA TEMPERATURE')
print('=' * 60)
print(f'Prompt: Classificar crime de furto durante sono da vítima')
print('-' * 60)

for temp, descricao in TEMPERATURAS:
    print(f'-> Processando a Temperature = {temp} ({descricao})...', end='', flush=True)
    inicio = time.time()

    resp = client_vllm.chat.completions.create(
        model=MODEL_ID,
        messages=[
            {'role': 'system', 'content': 'Você é um assistente jurídico técnico e objetivo.'},
            {'role': 'user',   'content': PROMPT_CLASSIFICACAO}
        ],
        temperature=temp,
        max_tokens=80,
    )

    duracao = time.time() - inicio
    texto   = resp.choices[0].message.content.strip()
    print()
    print(f'-> Resposta:  {texto}')
    print(f'-> Tempo:     {duracao:.1f}s | Tokens: {resp.usage.completion_tokens}')
    print('-' * 40)
    sys.stdout.flush() # Força a exibição imediata no Colab

print('\n🚀 Experimento finalizado!')

🌡️  EXPERIMENTO: IMPACTO DA TEMPERATURE
Prompt: Classificar crime de furto durante sono da vítima
------------------------------------------------------------
-> Processando a Temperature = 0.0 (Determinístico — máxima precisão)...
-> Resposta:  Classifico o crime como:

**Crime de Furto**

* **Artigo**: Artigo 169 do Código Penal Brasileiro
* **Pena máxima**: 2 a 6 anos de reclusão

O Artigo 169 do Código Penal Brasileiro define o crime de furto como "subtrair, para si ou para outrem, coisa
-> Tempo:     11.9s | Tokens: 80
----------------------------------------
-> Processando a Temperature = 0.3 (Baixo — recomendado para análise jurídica)...
-> Resposta:  Segundo o Código Penal Brasileiro, o crime descrito é o de Furto.

* Tipo do crime: Crime contra a propriedade.
* Artigo: Artigo 169 do Código Penal Brasileiro.
* Pena máxima: 4 anos de reclusão e/ou 4 dias-multa.
-> Tempo:     10.7s | Tokens: 71
----------------------------------------
-> Processando a Temperature = 0.7 (Médio — e

## 📦 CÉLULA 5 — API OpenAI-Compatível: System Messages e Roleplay Jurídico

**O que faz:** Demonstra o uso avançado de `system messages` para definir o papel do assistente jurídico.

**Por que:** Em sistemas RAG para direito e segurança pública, a `system message` define o "persona" do assistente — investigador, advogado, analista de inteligência. Esta separação é fundamental para controlar o comportamento do modelo em produção.

In [9]:
# ─── CÉLULA 5: System messages e roleplay jurídico ─────────────
import sys

print('🎭 DEMONSTRAÇÃO: SYSTEM MESSAGES PARA PERFIS JURÍDICOS')
print('=' * 60)

FATO_JURIDICO = (
    'Fato: Acusado foi preso em flagrante com 50g de cocaína dividida em '
    'embalagens individuais. Sem antecedentes criminais. Residência fixa comprovada.'
)

PERSONAS = [
    {
        'nome': '⚖️  JUIZ DE DIREITO',
        'system': (
            'Você é um juiz de direito. Analise os fatos sob a ótica da '
            'necessidade de decretação de prisão preventiva versus medidas cautelares alternativas. '
            'Seja objetivo. Cite apenas art. 319 CPP e 312 CPP.'
        ),
        'pergunta': 'Devo decretar prisão preventiva ou aplicar medidas cautelares alternativas?'
    },
    {
        'nome': '🔍 DELEGADO DE POLÍCIA',
        'system': (
            'Você é um delegado de polícia. Analise o flagrante e indique '
            'as diligências investigativas prioritárias a serem realizadas. '
            'Foque em cadeia de custódia e coleta de provas.'
        ),
        'pergunta': 'Quais diligências devo determinar imediatamente para fortalecer o inquérito?'
    },
    {
        'nome': '🧑‍💼 ADVOGADO DE DEFESA',
        'system': (
            'Você é um advogado criminal de defesa. Identifique '
            'as teses defensivas disponíveis e os argumentos para requerer '
            'liberdade provisória. Cite dispositivos legais aplicáveis.'
        ),
        'pergunta': 'Quais são as melhores teses de defesa disponíveis para este caso?'
    },
]

print(f'📋 Fato: {FATO_JURIDICO}')
print()

for persona in PERSONAS:
    print(f"{' ─ ' * 15}")
    print(f"👤 PERFIL: {persona['nome']}")
    print(f"❓ Pergunta: {persona['pergunta']}")
    print("⏳ Gerando resposta...")

    resp = client_vllm.chat.completions.create(
        model=MODEL_ID,
        messages=[
            {'role': 'system', 'content': persona['system']},
            {'role': 'user',   'content': f'{FATO_JURIDICO}\n\n{persona["pergunta"]}'}
        ],
        temperature=0.2,
        max_tokens=300,
    )

    print(f"\n{resp.choices[0].message.content.strip()}")
    print()

sys.stdout.flush()

print('=' * 60)
print('💡 INSIGHT ARQUITETURAL:')
print()
print('   O mesmo modelo Llama 3.1 8B produziu análises completamente diferentes')
print('   para o mesmo fato — apenas mudando a system message.')
print()
print('   Em sistemas RAG de produção, a system message é configurada por:')
print('   • Perfil do usuário logado (juiz, delegado, promotor, defensor)')
print('   • Contexto da operação (investigação criminal, processo judicial, inteligência)')
print('   • Nível de classificação dos documentos recuperados')


🎭 DEMONSTRAÇÃO: SYSTEM MESSAGES PARA PERFIS JURÍDICOS
📋 Fato: Fato: Acusado foi preso em flagrante com 50g de cocaína dividida em embalagens individuais. Sem antecedentes criminais. Residência fixa comprovada.

 ─  ─  ─  ─  ─  ─  ─  ─  ─  ─  ─  ─  ─  ─  ─ 
👤 PERFIL: ⚖️  JUIZ DE DIREITO
❓ Pergunta: Devo decretar prisão preventiva ou aplicar medidas cautelares alternativas?
⏳ Gerando resposta...

Como juiz de direito, analisando os fatos apresentados, considero que a prisão preventiva não é necessária nesse caso.

O art. 319 do Código de Processo Penal (CPP) estabelece que a prisão preventiva será decretada quando houver risco de perigo para a sociedade ou para a vítima, ou quando houver risco de obstrução da investigação ou da instrução processual. Nesse caso, não há indícios de que o acusado represente um perigo para a sociedade ou para a vítima.

Além disso, o art. 312 do CPP estabelece que, em caso de flagrante delito, o acusado pode ser preso, mas não há necessidade de prisão preven

## 📦 CÉLULA 6 — (Opcional) Expor vLLM via ngrok

**O que faz:** Cria um túnel ngrok para expor o servidor vLLM do Colab para acesso externo.

**Por que:** Permite que outros sistemas (sua máquina local, outro Colab, uma aplicação web) consumam o vLLM via URL pública HTTPS — mesma lógica usada no LAB 1 com o OpenSearch.

> **⚠️ Segurança:** A URL gerada pelo ngrok é pública. Nunca use dados reais sigilosos ao expor o servidor via ngrok. Use apenas para testes com dados fictícios.

### 🔑 Pré-requisito:
Adicione `NGROK_AUTHTOKEN` nos Segredos do Colab (token gratuito em https://dashboard.ngrok.com/authtokens)

In [ ]:
# ─── CÉLULA 6: Expor vLLM via ngrok (opcional) ────────────────
from pyngrok import ngrok, conf
import os

NGROK_TOKEN = get_secret('NGROK_AUTHTOKEN')

if not NGROK_TOKEN:
    print('ℹ️  NGROK_AUTHTOKEN não configurado — pulando exposição pública.')
    print('   Para usar: adicione NGROK_AUTHTOKEN nos Segredos do Colab.')
    VLLM_PUBLIC_URL = VLLM_URL  # Usa URL local como fallback
else:
    # Configura token ngrok
    conf.get_default().auth_token = NGROK_TOKEN

    # Abre túnel HTTP para a porta 8000 do vLLM
    tunnel = ngrok.connect(VLLM_PORT, 'http')
    VLLM_PUBLIC_URL = tunnel.public_url

    print('🌐 SERVIDOR vLLM EXPOSTO VIA NGROK')
    print('=' * 60)
    print(f'  URL pública:  {VLLM_PUBLIC_URL}')
    print(f'  Endpoint API: {VLLM_PUBLIC_URL}/v1/chat/completions')
    print(f'  Modelos:      {VLLM_PUBLIC_URL}/v1/models')
    print()

    # Testa a URL pública
    import requests
    try:
        r = requests.get(
            f'{VLLM_PUBLIC_URL}/v1/models',
            headers={'ngrok-skip-browser-warning': 'true'},
            timeout=10
        )
        if r.status_code == 200:
            modelos_pub = [m['id'] for m in r.json().get('data', [])]
            print(f'  ✅ API pública respondendo! Modelos: {modelos_pub}')
        else:
            print(f'  ❌ Falha: HTTP {r.status_code}')
    except Exception as e:
        print(f'  ❌ Erro na conexão: {e}')

    print()
    print('📋 Exemplo de uso externo (Python):')
    print(f'''
from openai import OpenAI

client = OpenAI(
    base_url='{VLLM_PUBLIC_URL}/v1',
    api_key='vllm-local',
    default_headers={{'ngrok-skip-browser-warning': 'true'}}
)

resp = client.chat.completions.create(
    model='{MODEL_ID}',
    messages=[{{"role": "user", "content": "Olá do exterior!"}}],
    temperature=0.2,
    max_tokens=100
)
print(resp.choices[0].message.content)
''')

### 🔧 Troubleshooting — Células 3 a 6:
| Erro | Causa | Solução |
|------|-------|---------|
| `Connection refused` na porta 8000 | Servidor vLLM não está ativo | Reexecute a Célula 2 |
| `The model meta-llama/... does not exist` | MODEL_ID incorreto | Consulte `client_vllm.models.list()` e use o id retornado |
| Respostas muito lentas (< 5 tok/s) | Modelo usando CPU | Reinicie runtime; confirme GPU ativa |
| `ngrok.exceptions.PyngrokNgrokAuthError` | Token ngrok inválido | Gere novo token em dashboard.ngrok.com |
| `max_tokens` excedido silenciosamente | `finish_reason = length` | Aumente `max_tokens` ou reduza o contexto do prompt |

## ✅ CÉLULA 7 — Checklist de Validação

**Execute esta célula ao final para confirmar que todos os objetivos do Lab 3 foram atingidos.**

In [ ]:
# ─── CÉLULA 7: Checklist de validação ─────────────────────────
import requests, subprocess, time

print('✅ CHECKLIST DE VALIDAÇÃO — LAB 3 (vLLM + Llama 3.1 8B)')
print('=' * 65)

checks = []

# ── Check 1: vLLM instalado ───────────────────────────────────
try:
    import vllm
    checks.append(('vLLM instalado',
                   True, f'Versão: {vllm.__version__}'))
except ImportError:
    checks.append(('vLLM instalado', False, 'Reexecute a Célula 1'))

# ── Check 2: Servidor vLLM respondendo na porta 8000 ─────────
try:
    r = requests.get(f'{VLLM_URL}/health', timeout=5)
    checks.append(('Servidor vLLM ativo (porta 8000)',
                   r.status_code == 200,
                   f'HTTP {r.status_code}'))
except Exception as e:
    checks.append(('Servidor vLLM ativo (porta 8000)', False, str(e)[:50]))

# ── Check 3: Modelo Llama 3.1 carregado ──────────────────────
try:
    r = requests.get(f'{VLLM_URL}/v1/models', timeout=5)
    modelos_ids = [m['id'] for m in r.json().get('data', [])]
    tem_llama = any('llama' in m.lower() or 'Meta-Llama' in m for m in modelos_ids)
    checks.append(('Modelo Llama 3.1 8B carregado',
                   tem_llama,
                   f'Modelos: {modelos_ids}'))
except Exception as e:
    checks.append(('Modelo Llama 3.1 8B carregado', False, str(e)[:50]))

# ── Check 4: Primeiro completion executado ────────────────────
try:
    resp_test = client_vllm.chat.completions.create(
        model=MODEL_ID,
        messages=[{'role': 'user', 'content': 'Diga apenas: OK'}],
        temperature=0.0,
        max_tokens=10,
    )
    resposta_ok = resp_test.choices[0].message.content.strip()
    checks.append(('API /v1/chat/completions funcional',
                   len(resposta_ok) > 0,
                   f'Resposta: "{resposta_ok[:30]}"'))
except Exception as e:
    checks.append(('API /v1/chat/completions funcional', False, str(e)[:60]))

# ── Check 5: Velocidade de geração ───────────────────────────
try:
    inicio = time.time()
    resp_bench = client_vllm.chat.completions.create(
        model=MODEL_ID,
        messages=[{'role': 'user', 'content': 'Liste 5 artigos do Código Penal.'}],
        temperature=0.1,
        max_tokens=100,
    )
    duracao_bench = time.time() - inicio
    tok_bench     = resp_bench.usage.completion_tokens
    tok_s         = tok_bench / duracao_bench if duracao_bench > 0 else 0
    checks.append(('Velocidade de geração > 10 tokens/s',
                   tok_s > 10,
                   f'{tok_s:.1f} tokens/s ({tok_bench} tokens em {duracao_bench:.1f}s)'))
except Exception as e:
    checks.append(('Velocidade de geração > 10 tokens/s', False, str(e)[:60]))

# ── Check 6: API OpenAI-compatível (cliente openai) ───────────
try:
    from openai import OpenAI
    client_check = OpenAI(base_url=f'{VLLM_URL}/v1', api_key='test')
    lista = client_check.models.list()
    checks.append(('Cliente OpenAI SDK compatível',
                   len(lista.data) > 0,
                   f'{len(lista.data)} modelo(s) listado(s)'))
except Exception as e:
    checks.append(('Cliente OpenAI SDK compatível', False, str(e)[:60]))

# ── Check 7: Exposição ngrok (opcional) ──────────────────────
ngrok_ativo = VLLM_PUBLIC_URL != VLLM_URL
checks.append(('Túnel ngrok ativo (opcional)',
               ngrok_ativo,
               VLLM_PUBLIC_URL if ngrok_ativo else 'Não configurado (opcional)'))

# ── Imprime resultado ────────────────────────────────────────
aprovados = sum(1 for _, ok, _ in checks if ok)
total     = len(checks)

for nome, ok, detalhe in checks:
    icone = '✅' if ok else '❌'
    print(f'{icone} {nome}')
    print(f'   {detalhe}')

print()
print('=' * 65)
obrigatorios = sum(1 for i, (_, ok, _) in enumerate(checks) if ok and i < 6)
print(f'Obrigatórios: {obrigatorios}/6 | Opcional (ngrok): {"✅" if ngrok_ativo else "—"}')

if obrigatorios == 6:
    print()
    print('🎉 PARABÉNS! Lab 3 concluído com sucesso!')
    print('   O servidor vLLM com Llama 3.1 8B está operacional.')
    print('   Próximo: Lab 4 — LangFuse para observabilidade das gerações.')
else:
    print()
    print('⚠️  Alguns checks falharam. Consulte o troubleshooting de cada célula.')

---

## 📚 Conceitos Consolidados neste Lab

| Conceito | O que foi praticado |
|----------|--------------------|
| **vLLM** | Servidor de inferência de alta performance com PagedAttention |
| **API OpenAI-compatível** | `/v1/chat/completions` — mesmo padrão do GPT-4 |
| **System Messages** | Controle de comportamento via persona jurídica |
| **Temperature** | Impacto na variabilidade e precisão das respostas |
| **Tokens e Métricas** | `prompt_tokens`, `completion_tokens`, tokens/s |
| **ngrok** | Exposição segura do servidor local para acesso externo |
| **HuggingFace Hub** | Download e servição de modelos licenciados |

---

## 🔗 Referências

KWON, Woosuk et al. **Efficient Memory Management for Large Language Model Serving with PagedAttention**. In: *Proceedings of the ACM SIGOPS 29th Symposium on Operating Systems Principles*, 2023. Disponível em: https://arxiv.org/abs/2309.06180. Acesso em: abr. 2026.

META AI. **Llama 3.1 Model Card**. 2024. Disponível em: https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct. Acesso em: abr. 2026.

VLLM PROJECT. **vLLM: Easy, Fast, and Cheap LLM Serving with PagedAttention**. GitHub, 2023. Disponível em: https://github.com/vllm-project/vllm. Acesso em: abr. 2026.